# Generated by Django 5.0.2 on 2024-02-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Title',
            field=models.CharField(default=1, max_length=60, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
