# Generated by Django 5.0.2 on 2024-02-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_articles_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60, verbose_name='Название')),
                ('Article', models.TextField(verbose_name='Статья')),
                ('ExampleImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60, verbose_name='Название')),
                ('Article', models.TextField(verbose_name='Статья')),
                ('ExampleImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Lang',
        ),
    ]
