# Generated by Django 5.0.2 on 2024-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_javascript_python_delete_articles_delete_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='ExampleImage',
            field=models.ImageField(upload_to='static/main/image'),
        ),
    ]
