# Generated by Django 5.0.2 on 2024-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_python_exampleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='ExampleImage',
            field=models.ImageField(upload_to='main/static/main/image'),
        ),
    ]
