# Generated by Django 5.0.2 on 2024-05-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_python_exampleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60, verbose_name='Название')),
                ('Article', models.TextField(verbose_name='Статья')),
                ('ExampleImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Langs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60, verbose_name='Название')),
            ],
        ),
        migrations.DeleteModel(
            name='JavaScript',
        ),
        migrations.DeleteModel(
            name='Python',
        ),
        migrations.AddField(
            model_name='info',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.langs'),
        ),
    ]
