# Generated by Django 5.0.2 on 2024-05-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_info_langs_delete_javascript_delete_python_info_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60, verbose_name='Название')),
                ('Article', models.TextField(verbose_name='Статья')),
                ('ExampleImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60, verbose_name='Название')),
                ('Article', models.TextField(verbose_name='Статья')),
                ('ExampleImage', models.ImageField(upload_to='main/static/main/image')),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Langs',
        ),
    ]
