# Generated by Django 5.0.2 on 2024-05-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_javascript_python_delete_info_delete_langs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascript',
            name='ExampleImage',
            field=models.ImageField(upload_to='main/static/main/image'),
        ),
    ]
