# Generated by Django 5.0.2 on 2024-05-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='AddPostForm',
        ),
    ]
