# Generated by Django 5.0.2 on 2024-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_reviews_addpostform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=16, verbose_name='ИМЯ')),
                ('Review', models.TextField(verbose_name='ОТЗЫВ')),
            ],
        ),
        migrations.DeleteModel(
            name='AddPostForm',
        ),
    ]
